// packages/vue-vantui-h5plus-boilerplate/src/App.vue
<!--
 * @Author: Cphayim
 * @Date: 2019-05-23 09:14:55
 * @LastEditTime: 2020-03-17 13:32:56
 * @Description: 入口组件
-->

<template>
  <div id="app">
    <RouterTransition>
      <keep-alive :include="keepAliveComponents">
        <router-view />
      </keep-alive>
    </RouterTransition>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import RouterTransition from '@/components/common/router-transition.vue'
export default {
  name: 'App',
  components: { RouterTransition },
  computed: {
    // 动态添加移除的 keepalive 列表
    ...mapState(['keepAliveComponents']),
  },
  data() {
    return {}
  },
}
</script>

// packages/react-antd-typescript-boilerplate/src/App.tsx
/*
 * @Author: Cphayim
 * @Date: 2020-07-14 15:52:34
 * @LastEditTime: 2020-07-15 15:56:57
 * @Description: 入口组件
 */
import React from 'react'
import { Provider } from 'react-redux'

import { store } from '@/store'
import routes from '@/router/routes'

import '@/App.scss'
import RouterView from './router/router-view'

export default function App() {
  return (
    <Provider store={store}>
      {/* <Counter label="label"></Counter> */}
      <RouterView routes={routes}></RouterView>
    </Provider>
  )
}
